### ISSUE TITLE
Add Link for Watered-Down Regex KB Article

### ISSUE THREAD

**Issue by kristineds** [websharks/wp-site-search#3]
In the Search Pattern field, it would be nice if we could add a link for the Watered-down Regex KB article which would help users who are not familiar with it. 

![screen shot 2016-09-16 at 11 39 31 pm](https://cloud.githubusercontent.com/assets/7514953/18591916/364b3d3e-7c67-11e6-8050-90a7c315fcd9.png)

**Comment by kristineds** [comment]
From [convo with @jaswsinc:](https://websharks.slack.com/archives/wp-site-search/p1474004506000008)

> Agree. We could just create a KBA outside of any product on the site and use that for multiple products

**Comment by kristineds** [comment]
@jaswsinc I've created [a draft](https://wpsharks.com/wp-admin/post.php?post=2136&action=edit) for the KB article. _(content taken from [previous KB article](https://cometcache.com/kb-article/watered-down-regex-syntax/))_

**Comment by jaswsinc** [comment]
@kristineds I approved the draft and make some edits.

---

**However,** please note, this field does not accept WRegx. The only character that is special in a Google CSE search pattern is the wildcard `*` asterisk.

**Comment by raamdev** [comment]
Moved here: https://github.com/websharks/wp-site-search-pro/issues/2
